"""Generate papasangre2/assets/schema.py from the PS2 class dump.

`-[PGELevel createObjectFromDict:]` applies every non-trigger level property by
building `set<Key>:` and asking the object `respondsToSelector:`; the ones that
answer go through `setValuesForKeysWithDictionary:` (KVC). So which keys a
level object accepts - and how KVC converts the string from the JSON - is
decided entirely by the class's setters and their argument types. This script
reads them out of the binary's own metadata (tools/classdump.txt), walking the
superclass chain, so the port answers `respondsToSelector:` exactly as the
original does.

For each setter it records the argument type (from the method's type
encoding) and whether it is a synthesized accessor or a hand-written method
with behaviour of its own (by its length in dis/all.txt), because the latter
must be ported as a method, not as a plain assignment.

    python gen_schema.py   -> ../papasangre2/assets/schema.py
"""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
DUMP = HERE / 'classdump.txt'
DIS = HERE / 'dis' / 'all.txt'
OUT = HERE.parent / 'papasangre2' / 'assets' / 'schema.py'

#: Tiled object type -> the class createObjectFromDict: builds (0x10003c35c).
TYPE_CLASS = {
    'Room': 'PGELevel', 'Surface': 'PGESurface', 'Player': 'PGEPlayer',
    'Path': 'PGEPath', 'Sound': 'PGESound', 'Collectible': 'PGECollectible',
    'Monster': 'PGEEnemy', 'Follower': 'PGEFollower', 'Fireworks': 'PGEFireworks',
}

HEAD = re.compile(r'^@interface (\S+) : (\S+)')
METH = re.compile(r'^  - (set\w+:)\s+(\S+)\s+imp=0x([0-9a-f]+)')


def parse_dump():
    classes = {}
    cur = None
    for line in open(DUMP, encoding='utf-8', errors='replace'):
        m = HEAD.match(line)
        if m:
            cur = m.group(1)
            classes[cur] = {'super': m.group(2), 'setters': {}}
            continue
        if cur is None:
            continue
        m = METH.match(line)
        if m:
            sel, enc, imp = m.groups()
            # v20@0:8B16 -> the argument's encoding is what follows ":8"
            arg = re.sub(r'\d+', '', enc.split(':8', 1)[1]) if ':8' in enc else '?'
            classes[cur]['setters'][sel] = (arg[:1] if not arg.startswith('{') else arg, int(imp, 16))
    return classes


def method_lengths():
    lens = {}
    head = re.compile(r'^===== -\[(\S+) (\S+)\]  \((0x[0-9a-f]+)\)')
    cur = None
    for line in open(DIS, encoding='utf-8', errors='replace'):
        m = head.match(line)
        if m:
            cur = (m.group(1), m.group(2))
            lens[cur] = 0
        elif cur and line.startswith('0x'):
            lens[cur] += 1
    return lens


def main():
    classes = parse_dump()
    lens = method_lengths()
    out = ['"""GENERATED by tools/gen_schema.py from the Papa Sangre II class dump - do not edit.',
           '',
           'For every class the level loader builds: each `set<Key>:` it (or a superclass)',
           'answers, the setter\'s argument type code (f float, i int, B BOOL, @ object,',
           'd double, {...} a struct) and whether it is a hand-written method (`custom`)',
           'rather than a synthesized accessor. `-[PGELevel createObjectFromDict:]` applies',
           'a level property only when `respondsToSelector:` says yes (0x10003dda0).',
           '"""', '',
           'TYPE_CLASS = %r' % TYPE_CLASS, '',
           '#: class -> {selector: (type code, owning class, custom)}',
           'SETTERS = {']
    for cls in sorted(set(TYPE_CLASS.values())):
        merged = {}
        chain = []
        c = cls
        while c in classes:
            chain.append(c)
            c = classes[c]['super']
        for c in reversed(chain):                      # subclass overrides win
            for sel, (arg, imp) in classes[c]['setters'].items():
                n = lens.get((c, sel), 0)
                # a synthesized setter is a handful of instructions (objc_storeStrong
                # / a single store); anything longer does work of its own
                custom = n > (16 if arg == '@' else 8)
                merged[sel] = (arg, c, custom)
        out.append('    %r: {' % cls)
        for sel in sorted(merged):
            out.append('        %r: %r,' % (sel, merged[sel]))
        out.append('    },')
    out.append('}')
    out.append('')
    out.append('#: superclass chain, most derived first')
    out.append('CHAIN = {')
    for cls in sorted(set(TYPE_CLASS.values())):
        chain = []
        c = cls
        while c in classes:
            chain.append(c)
            c = classes[c]['super']
        out.append('    %r: %r,' % (cls, chain))
    out.append('}')
    OUT.write_text('\n'.join(out) + '\n', encoding='utf-8')
    print('wrote', OUT)


if __name__ == '__main__':
    main()
